### ISSUE TITLE
[BUG] Select button disabled when loaded inside IRRE

### ISSUE THREAD

**Issue by pixelmatseriks** [pixelant/qbank#11]
**Describe the bug**
The "Use media from QBank" button is disabled inside IRRE record when it is expanded and not loaded from the start.

**To Reproduce**

1. Edit a record that includes IRRE records with e.g. image.
2. Expand a collapsed IRRE record
3. If a IRRE record was expanded on load, button is enabled
![image](https://user-images.githubusercontent.com/5682324/119501094-d30c9e00-bd68-11eb-8671-dea16386a0ab.png)

4. If IRRE record is expanded, button is disabled
![image](https://user-images.githubusercontent.com/5682324/119501179-ea4b8b80-bd68-11eb-8390-ba3abbef27a7.png)

**Expected behavior**
Buttons should be enabled if it is possible to add an image.

**Screenshots**
See in description

**Desktop (please complete the following information):**

- OS: [Linux]
- Browser [Firefox]
- Version [88]

**Comment by MattiasNilsson** [comment]
Solved with https://github.com/pixelant/qbank/pull/16
